export const employees = Array.from({ length: 150 }).map((_, index) => {
  const departments = ["Vận hành", "Nhân sự", "Kế toán", "Kinh doanh", "Bếp", "Dịch vụ", "Marketing", "IT"];
  const positions = ["Nhân viên", "Trưởng nhóm", "Quản lý", "Chuyên viên", "Thực tập sinh"];
  return { id: `emp-${String(index + 1).padStart(3, "0")}`, code: `NV${String(index + 1).padStart(3, "0")}`, name: [`Minh Anh`, `Hoàng Nam`, `Gia Hân`, `Quốc Bảo`, `Thuỳ Linh`, `Đức Huy`, `Ngọc Mai`, `Thanh Sơn`][index % 8] + ` ${index + 1}`, department: departments[index % departments.length], position: positions[index % positions.length], status: index % 9 === 0 ? "Nghỉ phép" : index % 13 === 0 ? "Remote" : "Đang làm", email: `nhanvien${index + 1}@company.vn`, phone: `09${String(10000000 + index).slice(0,8)}`, joinDate: `202${index % 5}-0${(index % 9) + 1}-15` };
});
export const departments = [{ name: "Vận hành", headcount: 42, manager: "Nguyễn Minh Anh" },{ name: "Nhân sự", headcount: 12, manager: "Trần Gia Hân" },{ name: "Kế toán", headcount: 8, manager: "Lê Thuỳ Linh" },{ name: "Kinh doanh", headcount: 28, manager: "Phạm Quốc Bảo" },{ name: "Bếp", headcount: 34, manager: "Võ Đức Huy" },{ name: "Dịch vụ", headcount: 26, manager: "Đỗ Ngọc Mai" }];
export const shifts = [{ name: "Ca sáng", time: "08:00 - 16:00", status: "Đang diễn ra" },{ name: "Ca chiều", time: "14:00 - 22:00", status: "Sắp tới" },{ name: "Ca gãy", time: "10:00 - 14:00 / 18:00 - 22:00", status: "Linh hoạt" }];
export const approvals = [{ title: "Đơn nghỉ phép - Nguyễn Minh Anh", type: "Nghỉ phép", status: "Chờ duyệt", date: "Hôm nay" },{ title: "Điều chỉnh chấm công - NV023", type: "Chấm công", status: "Cần xem", date: "Hôm qua" },{ title: "Đăng ký tăng ca - Team Bếp", type: "Tăng ca", status: "Chờ duyệt", date: "24/05" }];
export const notifications = [{ title: "Bạn có ca làm mới", subtitle: "Ca sáng ngày mai đã được phân công", tone: "blue" },{ title: "Đơn nghỉ phép đã được duyệt", subtitle: "Quản lý trực tiếp đã phê duyệt", tone: "green" },{ title: "Cảnh báo chấm công muộn", subtitle: "Bạn vào ca trễ 12 phút", tone: "orange" }] as const;
export const candidates = Array.from({ length: 18 }).map((_, index) => ({ id: `cand-${index + 1}`, name: [`Lan Anh`, `Minh Khang`, `Hà Phương`, `Tuấn Kiệt`, `Bảo Ngọc`, `Hoài Nam`][index % 6], role: [`Nhân viên phục vụ`, `HR Executive`, `Kế toán tổng hợp`, `Bếp chính`][index % 4], stage: [`CV mới`, `Sơ loại`, `Phỏng vấn`, `Offer`][index % 4], score: 70 + (index % 25) }));
export const kpis = [{ label: "Hiện diện", value: "96%" },{ label: "Đúng giờ", value: "92%" },{ label: "Hoàn thành OKR", value: "78%" },{ label: "Đào tạo", value: "84%" }];
